# Project metadata
sonar.projectKey=ConnectSphere
sonar.projectName=ConnectSphere
sonar.projectVersion=1.0

# Path to the source code
# Since we use dotnet-sonarscanner for C#, this generic scanner will focus on the frontend
sonar.sources=frontend/src
sonar.exclusions=frontend/node_modules/**, frontend/dist/**, **/*.test.jsx, **/*.test.js, frontend/src/assets/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript specific settings
sonar.javascript.environments=browser,node
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
